### ISSUE TITLE
Three separate sentences aligned as two sentences

### ISSUE THREAD

**Issue by echan00** [rsennrich/Bleualign#33]
I see a condition where two separate sentences were merged as one sentence in the alignment file. Is this expected?

Original.txt .   (3 separate sentences):
```
(2) in the event of a Settlement Disruption Event, the Settlement Date.
“Distributor”
Means those intermediaries licensed by the SFC and appointed from time to time by the Placing Agent.
```

Original.txt-t   (2 sentences):
```
(2) in the event of a Settlement Disruption Event, the Settlement Date. “Distributor”
Means those intermediaries licensed by the SFC and appointed from time to time by the Placing Agent.
```

Notice "Distributor" was appended to the end of the first line instead of staying as a sentence of its own.

**Comment by rsennrich** [comment]
This is a feature - there is an n-to-1 alignment heuristic that merges two consecutive sentences if this increases bleu (and adds at least one n-gram match to avoid merges due to the brevity penalty). You can disable this behavior if you want by setting the flag in the script to 1: https://github.com/rsennrich/Bleualign/blob/9183c042ffd2ce235972e9aeb253d376cfaeed5b/bleualign/align.py#L101

**Comment by echan00** [comment]
Understood! Thanks
